info:
  appName: ${spring.application.name}
  appDesc: 'SrpingBoot Test'
  groupId: '@project.groupId@'
  artifactId: '@project.artifactId@'
  version: '@project.version@'

  #
  school:
    name: nohi-demo

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志
    map-underscore-to-camel-case: true
    # 该配置就是将带有下划线的表字段映射为驼峰格式的实体类属性
  mapper-locations: classpath*:/nohi/boot/demo/**/*.xml
#  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      property-format: "\"%s\""
spring:
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    prefix: classpath:/templates
    servlet:
      content-type: text/html
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test_mybatis_plus?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8&rewriteBatchedStatements=true
    username: root
    password: root1234

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: nohi.boot.demo.web
  default-flat-param-object: true

knife4j:
  enable: true

logging:
  level:
    nohi.boot: debug
    org.apache.http.wire: debug
    org.apache.http.headers: debug
dingtalk:
  robot:
    appKey: ''
    appSecret: ''
    accessToken: '6b314ee33ed4227255220d85723992b661f7ca4d92f38cbf11539fc9e4b707a6'
    dingTalkServer: https://oapi.dingtalk.com
