package nohi.boot.demo.entity;

import com.alibaba.fastjson2.annotation.JSONField;
import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Data;
import lombok.Getter;
import lombok.Setter;

/**
 * This class was generated by NOHI MyBatis Generator.
 * This class corresponds to the database table CarMaintainHis
 */
@Data
@TableName("CAR_MAINTAIN_HIS")
public class CarMaintainHis {
    /**
     * CAR_MAINTAIN_HIS.ID
     */
    @TableId(value = "id", type = IdType.NONE)
    @JSONField(name = "ID")
    private String id;

    /**
     * CAR_MAINTAIN_HIS.A_ECMASTER_BX_AMT
     */
    @TableField("A_ECMASTER_BX_AMT")
    @JSONField(name = "A_ECMASTER_BX_AMT")
    private String aEcmasterBxAmt;



    /**
     * CAR_MAINTAIN_HIS.A_BILL_DATE
     */
    @TableField("A_BILL_DATE")
    @JSONField(name = "A_BILL_DATE")
    private String aBillDate;

    /**
     * CAR_MAINTAIN_HIS.A_ECMASTER_BX_CL_AMT
     */
    @TableField("A_ECMASTER_BX_CL_AMT")
    @JSONField(name = "A_ECMASTER_BX_CL_AMT")
    private String aEcmasterBxClAmt;

    /**
     * CAR_MAINTAIN_HIS.A_BILL_TYPE
     */
    @TableField("A_BILL_TYPE")
    @JSONField(name = "A_BILL_TYPE")
    private String aBillType;

    /**
     * CAR_MAINTAIN_HIS.A_AMT
     */
    @TableField("A_AMT")
    @JSONField(name = "A_AMT")
    private String aAmt;

    /**
     * CAR_MAINTAIN_HIS.A_ECMASTER_CARD_CL_AMT
     */
    @TableField("A_ECMASTER_CARD_CL_AMT")
    @JSONField(name = "A_ECMASTER_CARD_CL_AMT")
    private String aEcmasterCardClAmt;

    /**
     * CAR_MAINTAIN_HIS.A_ECMASTER_SV_STATUS
     */
    @TableField("A_ECMASTER_SV_STATUS")
    @JSONField(name = "A_ECMASTER_SV_STATUS")
    private String aEcmasterSvStatus;

    /**
     * CAR_MAINTAIN_HIS.A_VEHICLEID_LICENSE_PLATE_CODE
     */
    @TableField("A_VEHICLEID_LICENSE_PLATE_CODE")
    @JSONField(name = "A_VEHICLEID_LICENSE_PLATE_CODE")
    private String aVehicleidLicensePlateCode;

    /**
     * CAR_MAINTAIN_HIS.A_TMP_ISBALANCE
     */
    @TableField("A_TMP_ISBALANCE")
    @JSONField(name = "A_TMP_ISBALANCE")
    private String aTmpIsbalance;

    /**
     * CAR_MAINTAIN_HIS.A_ECMASTER_CARD_AMT
     */
    @TableField("A_ECMASTER_CARD_AMT")
    @JSONField(name = "A_ECMASTER_CARD_AMT")
    private String aEcmasterCardAmt;

    /**
     * CAR_MAINTAIN_HIS.A_ECMASTER_SB_GS_AMT
     */
    @TableField("A_ECMASTER_SB_GS_AMT")
    @JSONField(name = "A_ECMASTER_SB_GS_AMT")
    private String aEcmasterSbGsAmt;

    /**
     * CAR_MAINTAIN_HIS.A_ECMASTER_KILOMETRE
     */
    @TableField("A_ECMASTER_KILOMETRE")
    @JSONField(name = "A_ECMASTER_KILOMETRE")
    private String aEcmasterKilometre;

    /**
     * CAR_MAINTAIN_HIS.A_ECMASTER_BX_GS_AMT
     */
    @TableField("A_ECMASTER_BX_GS_AMT")
    @JSONField(name = "A_ECMASTER_BX_GS_AMT")
    private String aEcmasterBxGsAmt;

    /**
     * CAR_MAINTAIN_HIS.A_DEPTID_ACCTTYPE_ACCT_TYPE
     */
    @TableField("A_DEPTID_ACCTTYPE_ACCT_TYPE")
    @JSONField(name = "A_DEPTID_ACCTTYPE_ACCT_TYPE")
    private String aDeptidAccttypeAcctType;

    /**
     * CAR_MAINTAIN_HIS.A_ECMASTER_SB_AMT
     */
    @TableField("A_ECMASTER_SB_AMT")
    @JSONField(name = "A_ECMASTER_SB_AMT")
    private String aEcmasterSbAmt;

    /**
     * CAR_MAINTAIN_HIS.A_ECMASTER_SB_CL_AMT
     */
    @TableField("A_ECMASTER_SB_CL_AMT")
    @JSONField(name = "A_ECMASTER_SB_CL_AMT")
    private String aEcmasterSbClAmt;

    /**
     * CAR_MAINTAIN_HIS.A_VEHICLEID_ITEMID_ITEM_NAME
     */
    @TableField("A_VEHICLEID_ITEMID_ITEM_NAME")
    @JSONField(name = "A_VEHICLEID_ITEMID_ITEM_NAME")
    private String aVehicleidItemidItemName;

    /**
     * CAR_MAINTAIN_HIS.A_ECMASTER_SB_CLHS_AMT
     */
    @TableField("A_ECMASTER_SB_CLHS_AMT")
    @JSONField(name = "A_ECMASTER_SB_CLHS_AMT")
    private String aEcmasterSbClhsAmt;

    /**
     * CAR_MAINTAIN_HIS.A_STAFFID_STAFF_NAME
     */
    @TableField("A_STAFFID_STAFF_NAME")
    @JSONField(name = "A_STAFFID_STAFF_NAME")
    private String aStaffidStaffName;

    /**
     * CAR_MAINTAIN_HIS.A_ECMASTER_CARD_GS_AMT
     */
    @TableField("A_ECMASTER_CARD_GS_AMT")
    @JSONField(name = "A_ECMASTER_CARD_GS_AMT")
    private String aEcmasterCardGsAmt;

    /**
     * CAR_MAINTAIN_HIS.A_TTL_AMT
     */
    @TableField("A_TTL_AMT")
    @JSONField(name = "A_TTL_AMT")
    private String aTtlAmt;

    /**
     * CAR_MAINTAIN_HIS.A_DEPTID_DEPT_NAME
     */
    @TableField("A_DEPTID_DEPT_NAME")
    @JSONField(name = "A_DEPTID_DEPT_NAME")
    private String aDeptidDeptName;

    /**
     * CAR_MAINTAIN_HIS.A_BILL_ID
     */
    @TableField("A_BILL_ID")
    @JSONField(name = "A_BILL_ID")
    private String aBillId;

    /**
     * CAR_MAINTAIN_HIS.A_ORTHER_AMT
     */
    @TableField("A_ORTHER_AMT")
    @JSONField(name = "A_ORTHER_AMT")
    private String aOrtherAmt;

    /**
     * CAR_MAINTAIN_HIS.A_VEHICLEID_CUSTID_CUST_NAME
     */
    @TableField("A_VEHICLEID_CUSTID_CUST_NAME")
    @JSONField(name = "A_VEHICLEID_CUSTID_CUST_NAME")
    private String aVehicleidCustidCustName;

    /**
     * CAR_MAINTAIN_HIS.A_ECMASTER_DRIVER_TEL
     */
    @TableField("A_ECMASTER_DRIVER_TEL")
    @JSONField(name = "A_ECMASTER_DRIVER_TEL")
    private String aEcmasterDriverTel;

    /**
     * CAR_MAINTAIN_HIS.A_ECMASTER_SVTYPE_DESCRIPTION
     */
    @TableField("A_ECMASTER_SVTYPE_DESCRIPTION")
    @JSONField(name = "A_ECMASTER_SVTYPE_DESCRIPTION")
    private String aEcmasterSvtypeDescription;

    /**
     * CAR_MAINTAIN_HIS.A_ECMASTER_GS_AMT
     */
    @TableField("A_ECMASTER_GS_AMT")
    @JSONField(name = "A_ECMASTER_GS_AMT")
    private String aEcmasterGsAmt;

    /**
     * CAR_MAINTAIN_HIS.A_BILL_NO
     */
    @TableField("A_BILL_NO")
    @JSONField(name = "A_BILL_NO")
    private String aBillNo;

    /**
     * CAR_MAINTAIN_HIS.A_STRIKE_AMT
     */
    @TableField("A_STRIKE_AMT")
    @JSONField(name = "A_STRIKE_AMT")
    private String aStrikeAmt;

}
