package nohi.boot.demo.entity;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import lombok.Getter;
import lombok.Setter;

import java.util.Date;

/**
 * Database Table Remarks:
 *   打卡记录
 *
 * This class was generated by NOHI MyBatis Generator.
 * This class corresponds to the database table TeamSign
 */
@Setter
@Getter
@TableName(value = "TEAM_SIGN")
public class TeamSign {
    /**
     *   id主键
     *   TEAM_SIGN.id
     */
    @TableId(value = "id", type = IdType.ASSIGN_ID)
    private String id;

    /**
     *   用户id
     *   TEAM_SIGN.user_id
     */
    @TableField("user_id")
    private String userId;

    /**
     *   打卡日期
     *   TEAM_SIGN.date
     */
    private Date date;

    /**
     *   打卡时间
     *   TEAM_SIGN.time
     */
    private String time;

    /**
     *   打卡时间戳
     *   TEAM_SIGN.sign_time
     */
    @TableField("sign_time")
    private Date signTime;
}
