package nohi.boot.kqjs.entity;

import com.baomidou.mybatisplus.annotation.TableName;
import lombok.Getter;
import lombok.Setter;

import java.util.Date;

/**
 * Database Table Remarks:
 * 群报数打卡数据
 * <p>
 * This class was generated by NOHI MyBatis Generator.
 * This class corresponds to the database table KqQun100
 *
 * @author nohi
 */
@Setter
@Getter
@TableName("KQ_QUN_100")
public class KqQun100 {
    /**
     * 记录创建时间
     * KQ_QUN_100.CREATED_TS
     */
    private Date createdTs;

    /**
     * 工作日
     * KQ_QUN_100.WORK_DATE
     */
    private Date workDate;

    /**
     * 姓名
     * KQ_QUN_100.USERNAME
     */
    private String username;

    /**
     * 打卡时间-门禁
     * KQ_QUN_100.CARD_TIME_DOOR
     */
    private Date cardTimeDoor;

    /**
     * 打卡时间-移动APP
     * KQ_QUN_100.CARD_TIME_APP
     */
    private Date cardTimeApp;

    /**
     * 备用字段1
     * KQ_QUN_100.REMARK1
     */
    private String remark1;

    /**
     * 备用字段2
     * KQ_QUN_100.REMARK2
     */
    private String remark2;
}
