package nohi.boot.kqjs.entity;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import lombok.Getter;
import lombok.Setter;

import java.util.Date;

/**
 * Database Table Remarks:
 * PUB_PARA
 * <p>
 * This class was generated by NOHI MyBatis Generator.
 * This class corresponds to the database table KqQun100
 *
 * @author nohhi
 */
@Setter
@Getter
@TableName("PUB_PARA")
public class PubPara {
    private String id;
    /**
     * 记录创建时间
     * KQ_QUN_100.CREATED_TS
     */
    private Date createdTs;
    private String paraName;
    private String paraValue;
    /**
     * 备用字段1
     * KQ_QUN_100.REMARK1
     */
    private String remark1;

    /**
     * 备用字段2
     * KQ_QUN_100.REMARK2
     */
    private String remark2;
}
